apiVersion: v1
kind: Service
metadata:
  name: crm-api
  namespace: sahi
spec:
  type: ClusterIP
  selector:
    app: crm-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-api
  namespace: sahi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-api
  template:
    metadata:
      labels:
        app: crm-api
    spec:
      imagePullSecrets:
        - name: pruregistry
      serviceAccountName: sahi-microservice
      containers:
        - name: crm-api
          image: docker-phil-sahi-local.pruregistry.intranet.asia:8443/crm-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ORGANIZATION_CERT_BASE64
              valueFrom:
                secretKeyRef: 
                  name: sahi-certificates
                  key: ssl-cert	